# Generated by Django 5.1.1 on 2024-09-15 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitatAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('iframe_map', models.TextField(verbose_name='Код карты')),
            ],
            options={
                'verbose_name': 'Район обитания',
                'verbose_name_plural': 'Районы обитания',
            },
        ),
        migrations.CreateModel(
            name='TypeSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('short_description', models.TextField(verbose_name='Короткое описание')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы видов',
            },
        ),
        migrations.CreateModel(
            name='RedBookSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('main_photo', models.ImageField(upload_to='SpeciesGallery', verbose_name='Фотография')),
                ('description', models.TextField(verbose_name='Описание')),
                ('iframe_map', models.TextField(verbose_name='Код карты')),
                ('habitat_area', models.ManyToManyField(to='main.habitatareas', verbose_name='Районы обитания')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.typespecies', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Вид',
                'verbose_name_plural': 'Виды, занесенные в красную книгу',
            },
        ),
        migrations.CreateModel(
            name='SpeciesGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='SpeciesGallery', verbose_name='Фотография')),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.redbookspecies', verbose_name='Вид')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Галерея фотографий',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('favorite_species', models.ManyToManyField(related_name='user_favorities', to='main.redbookspecies', verbose_name='Фавориты из книги')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user_info', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи проекта',
            },
        ),
        migrations.CreateModel(
            name='UserGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='UserGallery', verbose_name='Фотография')),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.redbookspecies', verbose_name='Вид')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.userinfo', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Галерея пользовательских фото',
            },
        ),
    ]
