# Generated by Django 5.1.1 on 2024-09-18 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitatAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('iframe_map', models.TextField(verbose_name='Код карты')),
            ],
            options={
                'verbose_name': 'Район обитания',
                'verbose_name_plural': 'Районы обитания',
            },
        ),
        migrations.CreateModel(
            name='TypeSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('short_description', models.TextField(verbose_name='Короткое описание')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы видов',
            },
        ),
        migrations.CreateModel(
            name='RedBookSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('main_photo', models.ImageField(upload_to='SpeciesGallery', verbose_name='Фотография')),
                ('photo_autor', models.CharField(default='', max_length=100, verbose_name='Автор фото')),
                ('international_name', models.TextField(default='', verbose_name='Муждународное название')),
                ('status', models.TextField(default='', verbose_name='Статус')),
                ('spreading', models.TextField(default='', verbose_name='Распространение')),
                ('pop_count', models.TextField(default='', verbose_name='Численность')),
                ('habitat_features', models.TextField(default='', verbose_name='Особенности обитания')),
                ('limit_features', models.TextField(default='', verbose_name='Лимитирующие факторы')),
                ('protect_step', models.TextField(default='', verbose_name='Принятые меры охраны')),
                ('state_change', models.TextField(default='', verbose_name='Изменение состояния')),
                ('necessary_measures', models.TextField(default='', verbose_name='Необходимые меры охраны')),
                ('sources', models.TextField(default='', verbose_name='Источники')),
                ('autor', models.TextField(default='', verbose_name='Автор')),
                ('additional_info', models.TextField(blank=True, default='', verbose_name='Дополнительная информация')),
                ('iframe_map', models.TextField(verbose_name='Код карты')),
                ('habitat_area', models.ManyToManyField(to='main.habitatareas', verbose_name='Районы обитания')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.typespecies', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Вид',
                'verbose_name_plural': 'Виды, занесенные в красную книгу',
            },
        ),
        migrations.CreateModel(
            name='SpeciesGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='SpeciesGallery', verbose_name='Фотография')),
                ('autor', models.CharField(default='', max_length=100, verbose_name='Автор')),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gallery', to='main.redbookspecies', verbose_name='Вид')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Галерея фотографий',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('avatar', models.ImageField(blank=True, default=None, null=True, upload_to='UserAvatar', verbose_name='Фотография')),
                ('favorite_species', models.ManyToManyField(related_name='user_favorities', to='main.redbookspecies', verbose_name='Фавориты из книги')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user_info', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи проекта',
            },
        ),
        migrations.CreateModel(
            name='UserGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='UserGallery', verbose_name='Фотография')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='new', max_length=32, verbose_name='Статус')),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.redbookspecies', verbose_name='Вид')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_gallery', to='main.userinfo', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Галерея пользовательских фото',
            },
        ),
    ]
