# Generated by Django 5.1.1 on 2024-09-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='UserAvatar', verbose_name='Фотография'),
        ),
    ]
