# Generated by Django 5.1.1 on 2024-09-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='role',
            field=models.CharField(choices=[('admin', 'Админ'), ('user', 'Пользователь')], default='user', max_length=32, verbose_name='Роль'),
        ),
    ]
