# Generated by Django 5.1.1 on 2024-09-16 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userinfo_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redbookspecies',
            name='description',
        ),
        migrations.AddField(
            model_name='redbookspecies',
            name='autor',
            field=models.TextField(default='', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='redbookspecies',
            name='count',
            field=models.TextField(default='', verbose_name='Численность'),
        ),
        migrations.AddField(
            model_name='redbookspecies',
            name='descr_string_first',
            field=models.TextField(default='', verbose_name='Короткое описание строка 1'),
        ),
        migrations.AddField(
            model_name='redbookspecies',
            name='descr_string_second',
            field=models.TextField(default='', verbose_name='Короткое описание строка 2'),
        ),
        migrations.AddField(
            model_name='redbookspecies',
            name='descr_string_third',
            field=models.TextField(default='', verbose_name='Короткое описание строка 3'),
        ),
        migrations.AddField(
            model_name='redbookspecies',
            name='habitat_features',
            field=models.TextField(default='', verbose_name='Особенности обитания'),
        ),
        migrations.AddField(
            model_name='redbookspecies',
            name='limit_features',
            field=models.TextField(default='', verbose_name='Лимитирующие факторы'),
        ),
        migrations.AddField(
            model_name='redbookspecies',
            name='necessary_measures',
            field=models.TextField(default='', verbose_name='Необходимые меры охраны'),
        ),
        migrations.AddField(
            model_name='redbookspecies',
            name='photo_autor',
            field=models.TextField(default='', max_length=100, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='redbookspecies',
            name='protect_step',
            field=models.TextField(default='', verbose_name='Принятые меры охраны'),
        ),
        migrations.AddField(
            model_name='redbookspecies',
            name='sources',
            field=models.TextField(default='', verbose_name='Источники'),
        ),
        migrations.AddField(
            model_name='redbookspecies',
            name='spreading',
            field=models.TextField(default='', verbose_name='Распространение'),
        ),
        migrations.AddField(
            model_name='redbookspecies',
            name='state_change',
            field=models.TextField(default='', verbose_name='Изменение состояния'),
        ),
        migrations.AddField(
            model_name='redbookspecies',
            name='status',
            field=models.TextField(default='', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='speciesgallery',
            name='autor',
            field=models.CharField(default='', max_length=100, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='speciesgallery',
            name='specie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gallery', to='main.redbookspecies', verbose_name='Вид'),
        ),
    ]
