# Generated by Django 5.1.1 on 2024-09-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_families_squads_redbookspecies_family_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redbookspecies',
            name='international_name',
            field=models.CharField(default='', max_length=120, verbose_name='Муждународное название'),
        ),
    ]
