# Generated by Django 5.1.1 on 2024-09-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userinfo_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typespecies',
            options={'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы живых существ на сайте'},
        ),
        migrations.AddField(
            model_name='habitatareas',
            name='kadastr',
            field=models.CharField(default='', verbose_name='Кадастровый номер'),
        ),
        migrations.AlterField(
            model_name='families',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Название семейства'),
        ),
        migrations.AlterField(
            model_name='squads',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Название Отрядa/отделa/порядкa'),
        ),
        migrations.AlterField(
            model_name='typespecies',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Название раздела'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='favorite_species',
            field=models.ManyToManyField(blank=True, related_name='user_favorities', to='main.redbookspecies', verbose_name='Фавориты из книги'),
        ),
    ]
