# Generated by Django 5.1.1 on 2024-09-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_redbookspecies_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redbookspecies',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='redbookspecies',
            name='photo_autor',
            field=models.CharField(default='', max_length=100, verbose_name='Автор фото'),
        ),
    ]
