# Generated by Django 5.1.1 on 2024-09-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_redbookspecies_international_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='families',
            name='international_name',
            field=models.CharField(default='', max_length=64, verbose_name='Муждународное название'),
        ),
        migrations.AddField(
            model_name='squads',
            name='international_name',
            field=models.CharField(default='', max_length=64, verbose_name='Муждународное название'),
        ),
    ]
