# Generated by Django 5.1.1 on 2024-09-18 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_families_international_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='redbookspecies',
            name='actual_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='данные актуальны на'),
        ),
    ]
