# Generated by Django 5.1.1 on 2024-09-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_name_redbookspecies_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergallery',
            options={'verbose_name': 'Фотография', 'verbose_name_plural': 'Галерея пользовательских фото'},
        ),
        migrations.AddField(
            model_name='usergallery',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='new', max_length=32, verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
