# Generated by Django 5.1.1 on 2024-09-17 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_usergallery_options_usergallery_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redbookspecies',
            old_name='count',
            new_name='pop_count',
        ),
        migrations.AlterField(
            model_name='usergallery',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='new', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='usergallery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_gallery', to='main.userinfo', verbose_name='Пользователь'),
        ),
    ]
