# Generated by Django 5.1.1 on 2024-09-18 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_redbookspecies_actual_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redbookspecies',
            name='actual_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='данные актуальны на'),
        ),
    ]
