# Generated by Django 5.1.1 on 2024-09-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_redbookspecies_actual_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redbookspecies',
            name='habitat_area',
            field=models.ManyToManyField(related_name='red_book_species', to='main.habitatareas', verbose_name='Районы обитания'),
        ),
    ]
